const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={view:'home',files:[]};
const fine=matchMedia('(hover:hover) and (pointer:fine)').matches;
const hashNative=!!(window.crypto&&window.crypto.subtle);
const MAX_FILES=20;
function esc(s){return String(s).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function fmt(n){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';if(n<1073741824)return(n/1048576).toFixed(1)+' MB';return(n/1073741824).toFixed(2)+' GB'}
function iconKind(f){const n=f.name.toLowerCase();if(/\.(png|jpe?g|gif|webp|heic|bmp|tiff?)$/.test(n))return'IMG';if(/\.pdf$/.test(n))return'PDF';if(/\.(docx?|odt|rtf)$/.test(n))return'DOC';if(/\.(xlsx?|ods|csv|tsv)$/.test(n))return'DATA';if(/\.(pptx?|odp)$/.test(n))return'SLIDE';if(/\.(zip|rar|7z|tar|gz|bz2|xz|zst)$/.test(n))return'ZIP';return'FILE'}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2200)}
function setView(v){state.view=v;$('#homeView').classList.toggle('hidden',v!=='home');$('#chatView').classList.toggle('active',v==='chat'||v==='workspace');$$('[data-view]').forEach(a=>a.classList.toggle('active',a.dataset.view===v));closeMenu();if(v==='workspace')toast('Workspace locale: vista unificata dell’interfaccia corrente.')}
let lastFocus=null;
function openMenu(){$('#sidebar').classList.add('open');$('#menuBtn').setAttribute('aria-expanded','true');$('#shade').classList.add('open')}
function closeMenu(){$('#sidebar').classList.remove('open');$('#menuBtn').setAttribute('aria-expanded','false');if(!$('#drawer').classList.contains('open'))$('#shade').classList.remove('open')}
function openSources(){lastFocus=document.activeElement;renderSources();$('#drawer').classList.add('open');$('#drawer').setAttribute('aria-hidden','false');$('#shade').classList.add('open');requestAnimationFrame(()=>$('#closeDrawer').focus())}
function closeSources(){const wasOpen=$('#drawer').classList.contains('open');$('#drawer').classList.remove('open');$('#drawer').setAttribute('aria-hidden','true');if(!$('#sidebar').classList.contains('open'))$('#shade').classList.remove('open');if(wasOpen&&lastFocus&&typeof lastFocus.focus==='function')lastFocus.focus();lastFocus=null}
function syncVisualViewport(){const vv=window.visualViewport;const h=vv?Math.round(vv.height):window.innerHeight;const kb=vv?Math.max(0,Math.round(window.innerHeight-vv.height-vv.offsetTop)):0;const root=document.documentElement.style;root.setProperty('--vvh',h+'px');root.setProperty('--kb',kb+'px');document.body.classList.toggle('is-keyboard-open',kb>80)}
syncVisualViewport();window.visualViewport?.addEventListener('resize',syncVisualViewport);window.visualViewport?.addEventListener('scroll',syncVisualViewport);window.addEventListener('orientationchange',()=>setTimeout(syncVisualViewport,160));window.addEventListener('resize',syncVisualViewport);
{const c=$('.composer-wrap');if(c){const sync=()=>document.documentElement.style.setProperty('--composerh',c.offsetHeight+'px');sync();if(window.ResizeObserver)new ResizeObserver(sync).observe(c);else window.addEventListener('resize',sync)}}
const SHA256_K=new Uint32Array([0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2]);
class IncrementalSHA256{constructor(){this.h=new Uint32Array([0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19]);this.buf=new Uint8Array(64);this.bufLen=0;this.bytes=0;this.w=new Uint32Array(64)}rotr(x,n){return(x>>>n)|(x<<(32-n))}block(b){const w=this.w;for(let i=0;i<16;i++){const j=i*4;w[i]=((b[j]<<24)|(b[j+1]<<16)|(b[j+2]<<8)|b[j+3])>>>0}for(let i=16;i<64;i++){const a=w[i-15],c=w[i-2],s0=(this.rotr(a,7)^this.rotr(a,18)^(a>>>3))>>>0,s1=(this.rotr(c,17)^this.rotr(c,19)^(c>>>10))>>>0;w[i]=(w[i-16]+s0+w[i-7]+s1)>>>0}let[a,b0,c,d,e,f,g,h]=this.h;for(let i=0;i<64;i++){const S1=(this.rotr(e,6)^this.rotr(e,11)^this.rotr(e,25))>>>0,ch=((e&f)^((~e)&g))>>>0,t1=(h+S1+ch+SHA256_K[i]+w[i])>>>0,S0=(this.rotr(a,2)^this.rotr(a,13)^this.rotr(a,22))>>>0,maj=((a&b0)^(a&c)^(b0&c))>>>0,t2=(S0+maj)>>>0;h=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b0;b0=a;a=(t1+t2)>>>0}this.h[0]=(this.h[0]+a)>>>0;this.h[1]=(this.h[1]+b0)>>>0;this.h[2]=(this.h[2]+c)>>>0;this.h[3]=(this.h[3]+d)>>>0;this.h[4]=(this.h[4]+e)>>>0;this.h[5]=(this.h[5]+f)>>>0;this.h[6]=(this.h[6]+g)>>>0;this.h[7]=(this.h[7]+h)>>>0}update(data){if(!(data instanceof Uint8Array))data=new Uint8Array(data);this.bytes+=data.length;let p=0;if(this.bufLen){const n=Math.min(64-this.bufLen,data.length);this.buf.set(data.subarray(0,n),this.bufLen);this.bufLen+=n;p+=n;if(this.bufLen===64){this.block(this.buf);this.bufLen=0}}while(p+64<=data.length){this.block(data.subarray(p,p+64));p+=64}if(p<data.length){this.buf.set(data.subarray(p),0);this.bufLen=data.length-p}return this}hex(){const b=this.buf;b[this.bufLen]=0x80;for(let i=this.bufLen+1;i<64;i++)b[i]=0;if(this.bufLen>=56){this.block(b);b.fill(0)}const hi=Math.floor(this.bytes/0x20000000)>>>0,lo=(this.bytes<<3)>>>0;b[56]=(hi>>>24)&255;b[57]=(hi>>>16)&255;b[58]=(hi>>>8)&255;b[59]=hi&255;b[60]=(lo>>>24)&255;b[61]=(lo>>>16)&255;b[62]=(lo>>>8)&255;b[63]=lo&255;this.block(b);return Array.from(this.h,x=>x.toString(16).padStart(8,'0')).join('')}}
async function digest(file,onProgress,signal){try{if(signal?.aborted)return'sha256-aborted';const nativeLimit=32*1024*1024;if(hashNative&&file.size<=nativeLimit){const buf=await file.arrayBuffer();if(signal?.aborted)return'sha256-aborted';const h=await crypto.subtle.digest('SHA-256',buf);if(signal?.aborted)return'sha256-aborted';onProgress?.(1);return[...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,'0')).join('')}const hasher=new IncrementalSHA256(),chunk=2*1024*1024,total=Math.max(file.size,1);for(let off=0;off<file.size;off+=chunk){if(signal?.aborted)return'sha256-aborted';const u8=new Uint8Array(await file.slice(off,Math.min(file.size,off+chunk)).arrayBuffer());if(signal?.aborted)return'sha256-aborted';hasher.update(u8);onProgress?.(Math.min(1,(off+u8.length)/total));await new Promise(r=>setTimeout(r,0))}if(signal?.aborted)return'sha256-aborted';if(file.size===0)onProgress?.(1);return hasher.hex()}catch{return signal?.aborted?'sha256-aborted':'sha256-unavailable'}}
function hashLabel(x){if(x.sha===null)return'SHA '+Math.round((x.progress||0)*100)+'%';if(x.sha==='sha256-unavailable')return'identità locale n/d';return'SHA '+x.sha.slice(0,10)+'…'}
function updateRow(x){const d=x.el;if(!d)return;d.querySelector('.meta small').textContent=fmt(x.file.size)+' · '+x.kind+' · '+hashLabel(x);const bar=d.querySelector('.progress');bar.hidden=x.sha!==null;bar.querySelector('i').style.width=Math.round((x.progress||0)*100)+'%'}
function createRow(x){const d=document.createElement('div');d.className='att';d.innerHTML=`<div class="fileico">${esc(x.kind[0])}</div><div class="meta"><b>${esc(x.file.name)}</b><small></small><div class="progress"><i></i></div></div><button class="rm" type="button" aria-label="Rimuovi ${esc(x.file.name)}">×</button>`;d.querySelector('.rm').onclick=()=>removeFile(x.id);x.el=d;$('#attachments').appendChild(d);updateRow(x)}
function removeFile(id){const i=state.files.findIndex(x=>x.id===id);if(i<0)return;const x=state.files[i];x.ctrl.abort();x.el?.remove();state.files.splice(i,1);renderSources()}
function renderSources(){const b=$('#sourceList');if(!state.files.length){b.innerHTML='<div class="empty">Nessun file allegato. Usa il pulsante + accanto al campo di messaggio.</div>';return}b.innerHTML=state.files.map((x,i)=>`<div class="source"><b>Allegato ${i+1} · ${esc(x.file.name)}</b><small>${esc(x.kind)} · ${esc(fmt(x.file.size))}</small><div class="hash">${x.sha&&x.sha!=='sha256-unavailable'?('sha256 '+esc(x.sha)):x.sha==='sha256-unavailable'?'identità locale non disponibile':'sha256 in calcolo…'}</div></div>`).join('')}
async function addFiles(files){let added=0,skipped=0;for(const f of files){if(state.files.length>=MAX_FILES){skipped++;continue}const x={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()),file:f,kind:iconKind(f),sha:null,progress:0,ctrl:new AbortController(),el:null};state.files.push(x);createRow(x);added++;digest(f,p=>{if(!x.ctrl.signal.aborted){x.progress=p;updateRow(x)}},x.ctrl.signal).then(h=>{if(x.ctrl.signal.aborted||h==='sha256-aborted'||!state.files.includes(x))return;const same=state.files.find(a=>a!==x&&a.sha===h&&h!=='sha256-unavailable');if(same){removeFile(x.id);toast('"'+f.name+'" ha lo stesso contenuto di "'+same.file.name+'": duplicato non aggiunto');return}x.sha=h;x.progress=1;updateRow(x);renderSources()})}$('#fileInput').value='';if(added)toast(added+(added===1?' file aggiunto':' file aggiunti'));if(skipped)toast('Limite di '+MAX_FILES+' file raggiunto: '+skipped+' ignorati');renderSources()}
let hashWasSuspended=false;function hashingInProgress(){return state.files.some(x=>x.sha===null&&!x.ctrl.signal.aborted)}document.addEventListener('visibilitychange',()=>{if(document.hidden){if(hashingInProgress())hashWasSuspended=true;return}if(!hashWasSuspended)return;hashWasSuspended=false;if(hashingInProgress())toast('Calcolo identità ripreso dopo la sospensione in background')});
function addMsg(role,html){const d=document.createElement('div');d.className='msg '+role;d.innerHTML=html;$('#messages').appendChild(d);d.scrollIntoView({block:'end',behavior:'smooth'})}
function clientStatus(){const p=state.files.length?`<b>${state.files.length} ${state.files.length===1?'file allegato':'file allegati'}.</b> L’identità locale viene calcolata quando disponibile. <b>Inferenza non collegata.</b>`:'<b>Inferenza non collegata.</b> Questa release pubblica registra la richiesta solo nell’interfaccia corrente e non genera ancora una risposta del modello.';addMsg('ai',`<div class="label">Stato client</div><p>${p}</p>`)}
function send(textOverride){const p=$('#prompt');const text=(textOverride??p.value).trim();if(!text&&!state.files.length)return;setView('chat');const shown=text||`File allegati: ${state.files.length}`;addMsg('user',`<p>${esc(shown)}</p>`);p.value='';clientStatus()}
$$('[data-view]').forEach(a=>a.onclick=e=>{e.preventDefault();setView(a.dataset.view)});$$('[data-prompt]').forEach(b=>b.onclick=()=>send(b.dataset.prompt));$('#menuBtn').setAttribute('aria-expanded','false');$('#menuBtn').onclick=openMenu;$('#sourceBtn').onclick=$('#navFiles').onclick=openSources;$('#closeDrawer').onclick=closeSources;$('#shade').onclick=()=>{closeMenu();closeSources()};$('#privacyBtn').onclick=()=>toast('Questa release pubblica non invia i file a un provider di inferenza.');$('#profileBtn').onclick=()=>toast('Profilo non configurato in questa build.');$('#fileInput').onchange=e=>addFiles([...e.target.files]);$('#sendBtn').onclick=()=>send();$('#prompt').addEventListener('keydown',e=>{if(fine&&e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$('#prompt').addEventListener('input',e=>{const max=document.body.classList.contains('is-keyboard-open')?96:130;e.target.style.height='44px';e.target.style.height=Math.min(e.target.scrollHeight,max)+'px'});$('#prompt').addEventListener('focus',()=>setTimeout(syncVisualViewport,140));$('#newChat').onclick=e=>{e.preventDefault();state.files.forEach(x=>x.ctrl.abort());state.files.length=0;$('#attachments').innerHTML='';renderSources();$('#messages').innerHTML='<div class="msg ai"><div class="label">Stato client</div><p><b>Interfaccia web pronta.</b> Puoi allegare file e calcolarne l’identità SHA-256. <b>Inferenza non collegata.</b></p></div>';setView('home')};
